/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.usuario;

/**
 *
 * @author fernando
 */
public class Seguro extends javax.swing.JFrame {

    /**
     * Creates new form Seguro
     */
    public Seguro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Seguro = new javax.swing.JTabbedPane();
        Inmobiliario = new javax.swing.JPanel();
        Vida = new javax.swing.JPanel();
        Seg = new javax.swing.JLabel();
        Clien = new javax.swing.JLabel();
        Direccion = new javax.swing.JLabel();
        Sal = new javax.swing.JButton();
        Reg = new javax.swing.JButton();
        ASeg = new javax.swing.JTextField();
        AClien = new javax.swing.JTextField();
        ADirec = new javax.swing.JTextField();
        ConsultaSeg = new javax.swing.JPanel();
        TCon = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Consultar = new javax.swing.JButton();
        BSal = new javax.swing.JButton();
        Automovil = new javax.swing.JPanel();
        LPlac = new javax.swing.JLabel();
        LClie = new javax.swing.JLabel();
        LSeg = new javax.swing.JLabel();
        BReg = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Placas = new javax.swing.JTextField();
        ID_cliente = new javax.swing.JTextField();
        ID_seguro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout InmobiliarioLayout = new javax.swing.GroupLayout(Inmobiliario);
        Inmobiliario.setLayout(InmobiliarioLayout);
        InmobiliarioLayout.setHorizontalGroup(
            InmobiliarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
        InmobiliarioLayout.setVerticalGroup(
            InmobiliarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        Seguro.addTab("Inmobiliario", Inmobiliario);

        Seg.setText("ID_seguro");

        Clien.setText("ID_Cliente");

        Direccion.setText("Direccion");

        Sal.setText("Salir");
        Sal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalActionPerformed(evt);
            }
        });

        Reg.setText("Registrar");
        Reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VidaLayout = new javax.swing.GroupLayout(Vida);
        Vida.setLayout(VidaLayout);
        VidaLayout.setHorizontalGroup(
            VidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VidaLayout.createSequentialGroup()
                        .addGroup(VidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Seg)
                            .addComponent(Clien)
                            .addComponent(Direccion))
                        .addGap(31, 31, 31)
                        .addGroup(VidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ADirec, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AClien, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ASeg, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(VidaLayout.createSequentialGroup()
                        .addComponent(Sal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                        .addComponent(Reg, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))))
        );
        VidaLayout.setVerticalGroup(
            VidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Seg)
                    .addComponent(ASeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(VidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clien, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AClien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(VidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ADirec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(VidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sal)
                    .addComponent(Reg))
                .addGap(54, 54, 54))
        );

        Seguro.addTab("Vida", Vida);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TCon.setViewportView(jTable1);

        Consultar.setText("Consultar");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });

        BSal.setText("Salir");

        javax.swing.GroupLayout ConsultaSegLayout = new javax.swing.GroupLayout(ConsultaSeg);
        ConsultaSeg.setLayout(ConsultaSegLayout);
        ConsultaSegLayout.setHorizontalGroup(
            ConsultaSegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConsultaSegLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(BSal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                .addComponent(Consultar)
                .addContainerGap())
            .addGroup(ConsultaSegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConsultaSegLayout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(TCon, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        ConsultaSegLayout.setVerticalGroup(
            ConsultaSegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConsultaSegLayout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addGroup(ConsultaSegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Consultar)
                    .addComponent(BSal))
                .addGap(61, 61, 61))
            .addGroup(ConsultaSegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConsultaSegLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TCon, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(123, Short.MAX_VALUE)))
        );

        Seguro.addTab("Consulta", ConsultaSeg);

        LPlac.setText("Placas");

        LClie.setText("Cliente");

        LSeg.setText("ID Seguro");

        BReg.setText("Registrar");
        BReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRegActionPerformed(evt);
            }
        });

        Salir.setText("Salir");

        javax.swing.GroupLayout AutomovilLayout = new javax.swing.GroupLayout(Automovil);
        Automovil.setLayout(AutomovilLayout);
        AutomovilLayout.setHorizontalGroup(
            AutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AutomovilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AutomovilLayout.createSequentialGroup()
                        .addGroup(AutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LPlac)
                            .addComponent(LClie)
                            .addComponent(LSeg))
                        .addGap(27, 27, 27)
                        .addGroup(AutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Placas)
                            .addComponent(ID_cliente)
                            .addComponent(ID_seguro, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(AutomovilLayout.createSequentialGroup()
                        .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                        .addComponent(BReg)
                        .addGap(48, 48, 48))))
        );
        AutomovilLayout.setVerticalGroup(
            AutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AutomovilLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(AutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LPlac)
                    .addComponent(Placas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LClie)
                    .addComponent(ID_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LSeg)
                    .addComponent(ID_seguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(AutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BReg)
                    .addComponent(Salir))
                .addGap(29, 29, 29))
        );

        Seguro.addTab("Automovil", Automovil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Seguro)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Seguro)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BRegActionPerformed

    private void SalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalActionPerformed

    private void RegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seguro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seguro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seguro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seguro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seguro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AClien;
    private javax.swing.JTextField ADirec;
    private javax.swing.JTextField ASeg;
    private javax.swing.JPanel Automovil;
    private javax.swing.JButton BReg;
    private javax.swing.JButton BSal;
    private javax.swing.JLabel Clien;
    private javax.swing.JPanel ConsultaSeg;
    private javax.swing.JButton Consultar;
    private javax.swing.JLabel Direccion;
    private javax.swing.JTextField ID_cliente;
    private javax.swing.JTextField ID_seguro;
    private javax.swing.JPanel Inmobiliario;
    private javax.swing.JLabel LClie;
    private javax.swing.JLabel LPlac;
    private javax.swing.JLabel LSeg;
    private javax.swing.JTextField Placas;
    private javax.swing.JButton Reg;
    private javax.swing.JButton Sal;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel Seg;
    private javax.swing.JTabbedPane Seguro;
    private javax.swing.JScrollPane TCon;
    private javax.swing.JPanel Vida;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
